{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-core
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
  ALLOW_WEBHOOKS: "{{ .Values.config.allowWebhooks }}"
  APP_DEBUG: "{{ .Values.config.app.debug }}"
  APP_ENV: "{{ .Values.config.app.env }}"
  APP_LOG_LEVEL: "{{ .Values.config.app.logLevel }}"
  APP_NAME: "{{ .Values.config.app.name }}"
  APP_URL: "{{ .Values.config.app.url }}"
  AUDIT_LOG_CHANNEL: "{{ .Values.config.auditLog.channel }}"
  AUDIT_LOG_LEVEL: "{{ .Values.config.auditLog.level }}"
  AUTHENTICATION_GUARD_EMAIL: "{{ .Values.config.authenticationGuard.email }}"
  AUTHENTICATION_GUARD_HEADER: "{{ .Values.config.authenticationGuard.header }}"
  AUTHENTICATION_GUARD: "{{ .Values.config.authenticationGuard.method }}"
  BROADCAST_DRIVER: "{{ .Values.config.broadcastDriver }}"
  CACHE_DRIVER: "{{ .Values.config.cache.driver }}"
  CACHE_PREFIX: "{{ .Values.config.cache.prefix }}"
  COOKIE_DOMAIN: "{{ .Values.config.cookie.domain }}"
  COOKIE_PATH: "{{ .Values.config.cookie.path }}"
  COOKIE_SAMESITE: "{{ .Values.config.cookie.samesite }}"
  COOKIE_SECURE: "{{ .Values.config.cookie.secure }}"
  CUSTOM_LOGOUT_URL: "{{ .Values.config.customLogoutURL }}"
  {{- if .Values.postgresql.enabled }}
  DB_CONNECTION: pgsql
  DB_HOST: "postgresql"
  DB_HOST: "{{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}"
  DB_PORT: "{{ .Values.postgresql.auth.port | default "5432" }}"
  DB_DATABASE: "{{ .Values.postgresql.auth.database }}"
  {{- else }}
  DB_CONNECTION: "{{ .Values.config.db.connection }}"
  DB_HOST: "{{ .Values.config.db.host }}"
  DB_PORT: "{{ .Values.config.db.port }}"
  DB_DATABASE: "{{ .Values.config.db.database }}"
  {{- end }}
  DB_SOCKET: "{{ .Values.config.db.socket }}"
  DEFAULT_LANGUAGE: "{{ .Values.config.default.language }}"
  DEFAULT_LOCALE: "{{ .Values.config.default.locale }}"
  DISABLE_CSP_HEADER: "{{ .Values.config.disable.cspHeader }}"
  DISABLE_FRAME_HEADER: "{{ .Values.config.disable.frameHeader }}"
  DKR_BUILD_LOCALE: "{{ .Values.config.dkr.buildLocale }}"
  DKR_CHECK_SQLITE: "{{ .Values.config.dkr.checkSqlite }}"
  ENABLE_EXCHANGE_RATES: "{{ .Values.config.enable.exchangeRates }}"
  ENABLE_EXTERNAL_MAP: "{{ .Values.config.enable.externalMap }}"
  ENABLE_EXTERNAL_RATES: "{{ .Values.config.enable.externalRates }}"
  FIREFLY_III_LAYOUT: "{{ .Values.config.fireflyIIIlayout }}"
  IPINFO_TOKEN: "{{ .Values.config.ipInfoToken }}"
  LOG_CHANNEL: "{{ .Values.config.log.channel }}"
  LOG_LEVEL: "{{ .Values.config.log.level }}"
  MAIL_ENCRYPTION: "{{ .Values.config.mail.encryption }}"
  MAIL_FROM: "{{ .Values.config.mail.from }}"
  MAIL_HOST: "{{ .Values.config.mail.host }}"
  MAIL_MAILER: "{{ .Values.config.mail.mailer }}"
  MAIL_PORT: "{{ .Values.config.mail.port }}"
  MAIL_SENDMAIL_COMMAND: "{{ .Values.config.mail.sendmailCommand }}"
  MAILGUN_DOMAIN: "{{ .Values.config.mailgun.domain }}"
  MAILGUN_ENDPOINT: "{{ .Values.config.mailgun.endpoint }}"
  MAP_DEFAULT_LAT: "{{ .Values.config.map.defaultLat }}"
  MAP_DEFAULT_LONG: "{{ .Values.config.map.defaultLong }}"
  MAP_DEFAULT_ZOOM: "{{ .Values.config.map.defaultZoom }}"
  # MYSQL_SSL_CA: "{{ .Values.config.mysql.ssl.ca }}"
  # MYSQL_SSL_CAPATH: "{{ .Values.config.mysql.ssl.caPath }}"
  # MYSQL_SSL_CERT: "{{ .Values.config.mysql.ssl.cert }}"
  # MYSQL_SSL_CIPHER: "{{ .Values.config.mysql.ssl.cipher }}"
  # MYSQL_SSL_KEY: "{{ .Values.config.mysql.ssl.key }}"
  # MYSQL_SSL_VERIFY_SERVER_CERT: "{{ .Values.config.mysql.ssl.verifyServerCert }}"
  # MYSQL_USE_SSL: "{{ .Values.config.mysql.ssl.enabled }}"
  PAPERTRAIL_HOST: "{{ .Values.config.papertrail.host }}"
  PAPERTRAIL_PORT: "{{ .Values.config.papertrail.port }}"
  {{- if or .Values.postgresql.enabled (eq .Values.config.db.connection "pgsql") }}
  PGSQL_SCHEMA: "{{ .Values.config.pgsql.schema }}"
  PGSQL_SSL_CERT: "{{ .Values.config.pgsql.ssl.cert }}"
  PGSQL_SSL_CRL_FILE: "{{ .Values.config.pgsql.ssl.crlFile }}"
  PGSQL_SSL_KEY: "{{ .Values.config.pgsql.ssl.key }}"
  PGSQL_SSL_MODE: "{{ .Values.config.pgsql.ssl.mode }}"
  PGSQL_SSL_ROOT_CERT: "{{ .Values.config.pgsql.ssl.rootCert }}"
  {{- end }}
  PUSHER_ID: "{{ .Values.config.pusher.id }}"
  PUSHER_KEY: "{{ .Values.config.pusher.key }}"
  PUSHER_SECRET: "{{ .Values.config.pusher.secret }}"
  QUEUE_DRIVER: "{{ .Values.config.queueDriver }}"
  REDIS_CACHE_DB: "{{ .Values.config.redis.cacheDb }}"
  REDIS_DB: "{{ .Values.config.redis.db }}"
  REDIS_HOST: "{{ .Values.config.redis.host }}"
  REDIS_PATH: "{{ .Values.config.redis.path }}"
  REDIS_PORT: "{{ .Values.config.redis.port }}"
  REDIS_SCHEME: "{{ .Values.config.redis.scheme }}"
  SEND_ERROR_MESSAGE: "{{ .Values.config.send.errorMessage }}"
  SEND_REPORT_JOURNALS: "{{ .Values.config.send.reportJournals }}"
  SESSION_DRIVER: "{{ .Values.config.sessionDriver }}"
  SITE_OWNER: "{{ .Values.config.siteOwner }}"
  TRACKER_URL: "{{ .Values.config.tracker.url }}"
  TRUSTED_PROXIES: "{{ .Values.config.trustedProxies }}"
  TZ: "{{ .Values.config.tz }}"
  VALID_URL_PROTOCOLS: "{{ .Values.config.validURLprotocols }}"
{{- end }}
