{{- if and (eq .Values.config.mail.existingSecret "") (or (ne .Values.config.mail.username "") (ne .Values.config.mail.password "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-mail
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.mail.username }}
  MAIL_USERNAME: {{ .Values.config.mail.username | b64enc | quote }}
{{- end }}
{{- if .Values.config.mail.password }}
  MAIL_PASSWORD: {{ .Values.config.mail.password | b64enc | quote }}
{{- end }}
{{- end }}
