{{- if and (eq .Values.config.pusher.existingSecret "") (or (ne .Values.config.pusher.id "") (ne .Values.config.pusher.key "") (ne .Values.config.pusher.secret "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-pusher
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.pusher.id }}
  PUSHER_ID: {{ .Values.config.pusher.id | b64enc | quote }}
{{- end }}
{{- if .Values.config.pusher.key }}
  PUSHER_KEY: {{ .Values.config.pusher.key | b64enc | quote }}
{{- end }}
{{- if .Values.config.pusher.secret }}
  PUSHER_SECRET: {{ .Values.config.pusher.secret | b64enc | quote }}
{{- end }}
{{- end }}
