apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 60 | trimSuffix "-" }}-db
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
{{- else }}
  DB_PASSWORD: {{ .Values.config.db.password | b64enc | quote }}
  DB_USERNAME: {{ .Values.config.db.username | b64enc | quote }}
{{- end }}
