{{- if and (eq .Values.config.passport.existingSecret "") (or (ne .Values.config.passport.privateKey "") (ne .Values.config.passport.publicKey "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-passport
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.passport.privateKey }}
  PASSPORT_PRIVATE_KEY: {{ .Values.config.passport.privateKey | b64enc | quote }}
{{- end }}
{{- if .Values.config.passport.publicKey }}
  PASSPORT_PUBLIC_KEY: {{ .Values.config.passport.publicKey | b64enc | quote }}
{{- end }}
{{- end }}
