{{- if and (eq .Values.config.mandrill.existingSecret "") (ne .Values.config.mandrill.secret "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-mandrill
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.mandrill.secret }}
  MANDRILL_SECRET: {{ .Values.config.mandrill.secret | b64enc | quote }}
{{- end }}
{{- end }}
