
{{- if (eq .Values.config.app.existingSecret "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 59 | trimSuffix "-" }}-app
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
  APP_KEY: {{ .Values.config.app.key | b64enc | quote }}
{{- end }}