{{- if and (eq .Values.config.demo.existingSecret "") (or (ne .Values.config.demo.username "") (ne .Values.config.demo.password "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-demo
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.demo.username }}
  DEMO_USERNAME: {{ .Values.config.demo.username | b64enc | quote }}
{{- end }}
{{- if .Values.config.demo.password }}
  DEMO_PASSWORD: {{ .Values.config.demo.password | b64enc | quote }}
{{- end }}
{{- end }}
