{{- if and (eq .Values.config.cronjob.existingSecret "") .Values.config.cronjob.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-cron
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
  STATIC_CRON_TOKEN: {{ .Values.config.cronjob.auth.token | b64enc | quote }}
{{- end }}
