{{- if and (eq .Values.config.sparkpost.existingSecret "") (ne .Values.config.sparkpost.secret "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-sparkpost
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.sparkpost.secret }}
  SPARKPOST_SECRET: {{ .Values.config.sparkpost.secret | b64enc | quote }}
{{- end }}
{{- end }}
