{{- if and (eq .Values.config.mailgun.existingSecret "") (ne .Values.config.mailgun.secret "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-mailgun
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.mailgun.secret }}
  MAILGUN_SECRET: {{ .Values.config.mailgun.secret | b64enc | quote }}
{{- end }}
{{- end }}
