{{- if and (eq .Values.config.ipInfo.existingSecret "") (ne .Values.config.ipInfo.token "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-ipinfo
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.ipInfo.token }}
  IPINFO_TOKEN: {{ .Values.config.ipInfo.token | b64enc | quote }}
{{- end }}
{{- end }}
