{{- if and (eq .Values.config.redis.existingSecret "") (or (ne .Values.config.redis.username "") (ne .Values.config.redis.password "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . | trunc 58 | trimSuffix "-" }}-redis
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
{{- if .Values.config.redis.username }}
  REDIS_USERNAME: {{ .Values.config.redis.username | b64enc | quote }}
{{- end }}
{{- if .Values.config.redis.password }}
  REDIS_PASSWORD: {{ .Values.config.redis.password | b64enc | quote }}
{{- end }}
{{- end }}
